"""Tests for Milestone 9.2: Excel Report Generation and Data Mapping."""

import io
from datetime import datetime, timezone
from decimal import Decimal
from uuid import UUID, uuid4

import openpyxl
import pytest

from app.services.document_metadata import CreatedDocumentMetadata
from app.services.export.data_mapper import (
    generate_export_filename,
    map_document_to_export_data,
)
from app.services.export.excel_generator import generate_document_excel_bytes
from app.services.export.schemas import (
    ExportDocumentData,
    ExportLineItem,
    ExportTaxComponent,
)

USER_ID = "78b63794-b748-43a8-8932-c532efaaab57"


def _make_sample_metadata(
    *,
    vendor: str = "D Mart (Avenue Supermarts Ltd)",
    address: str = "Sector 14, Gurgaon, Haryana 122001",
    date_str: str = "2026-07-29",
    invoice_no: str = "INV-2026-0891",
    subtotal: float = 950.00,
    discount: float = 50.00,
    tax: float = 115.60,
    total: float = 1015.60,
    line_items: list[dict] | None = None,
    tax_components: list[dict] | None = None,
    confidence_level: str = "HIGH",
    overall_confidence: float = 0.96,
    total_matches: bool = True,
) -> CreatedDocumentMetadata:
    if line_items is None:
        line_items = [
            {"description": "Organic Almond Milk 1L", "quantity": 2.0, "unit_price": 150.0, "line_total": 300.0},
            {"description": "Whole Wheat Bread 400g", "quantity": 1.0, "unit_price": 60.0, "line_total": 60.0},
            {"description": "Premium Extra Virgin Olive Oil 500ml with Cold Pressed Extraction", "quantity": 1.0, "unit_price": 590.0, "line_total": 590.0},
        ]
    if tax_components is None:
        tax_components = [
            {"name": "CGST", "rate": 6.0, "amount": 57.80},
            {"name": "SGST", "rate": 6.0, "amount": 57.80},
        ]

    doc_id = uuid4()
    return CreatedDocumentMetadata(
        id=doc_id,
        user_id=UUID(USER_ID),
        filename="receipt_dmart_july.png",
        storage_path=f"{USER_ID}/{doc_id}/original.png",
        content_type="image/png",
        size=245800,
        status="completed",
        created_at=datetime(2026, 7, 29, 14, 30, 0, tzinfo=timezone.utc),
        processed_at=datetime(2026, 7, 29, 14, 30, 5, tzinfo=timezone.utc),
        extraction_result={
            "vendor_company": vendor,
            "address": address,
            "date": date_str,
            "invoice_number": invoice_no,
            "subtotal": subtotal,
            "discount": discount,
            "taxable_amount": subtotal - discount,
            "tax": tax,
            "tax_components": tax_components,
            "service_charge": 0.0,
            "round_off": 0.0,
            "total": total,
            "line_items": line_items,
        },
        quality_result={
            "confidence_level": confidence_level,
            "overall_confidence": overall_confidence,
            "confidence_override": None,
            "needs_review": confidence_level != "HIGH",
            "mathematical_validation": {
                "validation_performed": True,
                "total_matches": total_matches,
                "calculated_total": total,
                "document_total": total,
                "difference": 0.0,
            },
            "issues": [],
        },
    )


# ─── 1. Basic Generation & Loadability ────────────────────────────────────────

def test_excel_generation_produces_valid_loadable_workbook() -> None:
    """Workbook is created in memory and can be reloaded cleanly by openpyxl."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)

    assert isinstance(excel_bytes, bytes)
    assert len(excel_bytes) > 1000

    # Load with openpyxl
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    assert "Document Report" in wb.sheetnames
    ws = wb["Document Report"]
    assert ws.max_row > 10
    assert ws.max_column >= 5


# ─── 2. STRUCTRA Branding ───────────────────────────────────────────────────

def test_excel_workbook_contains_structra_branding() -> None:
    """Workbook prominently displays STRUCTRA branding and subtitle."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    # Check top rows
    assert ws.cell(row=1, column=1).value == "STRUCTRA"
    subtitle_val = str(ws.cell(row=2, column=1).value or "").lower()
    assert "ai document intelligence" in subtitle_val

    # Check footer in last rows
    all_values = [str(cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]
    assert any("Generated by STRUCTRA" in val for val in all_values)


# ─── 3. Document & Vendor Information ────────────────────────────────────────

def test_document_and_vendor_information_mapping() -> None:
    """Vendor, address, dates, and invoice number are mapped accurately."""
    doc = _make_sample_metadata(
        vendor="Grand Plaza Hotel",
        address="Connaught Place, New Delhi",
        date_str="2026-03-18",
        invoice_no="GPH-8842",
    )
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    all_values = [str(cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]
    assert any("Grand Plaza Hotel" in val for val in all_values)
    assert any("Connaught Place, New Delhi" in val for val in all_values)
    assert any("2026-03-18" in val for val in all_values)
    assert any("GPH-8842" in val for val in all_values)
    assert any(str(doc.id) in val for val in all_values)


# ─── 4. Line Items Table ─────────────────────────────────────────────────────

def test_line_items_rendered_accurately_with_numeric_types() -> None:
    """Line items render descriptions, numeric quantities, unit prices, and line totals."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    # Collect row contents
    item_rows = []
    for row in ws.iter_rows(values_only=False):
        val_b = row[1].value  # Col B: Description
        if val_b in ["Organic Almond Milk 1L", "Whole Wheat Bread 400g", "Premium Extra Virgin Olive Oil 500ml with Cold Pressed Extraction"]:
            item_rows.append({
                "index": row[0].value,
                "desc": row[1].value,
                "qty": row[2].value,
                "unit_price": row[3].value,
                "line_total": row[4].value,
            })

    assert len(item_rows) == 3
    # Check 1st item
    assert item_rows[0]["desc"] == "Organic Almond Milk 1L"
    assert item_rows[0]["qty"] == 2.0
    assert item_rows[0]["unit_price"] == 150.0
    assert item_rows[0]["line_total"] == 300.0

    # Check 2nd item
    assert item_rows[1]["desc"] == "Whole Wheat Bread 400g"
    assert item_rows[1]["qty"] == 1.0
    assert item_rows[1]["unit_price"] == 60.0
    assert item_rows[1]["line_total"] == 60.0


# ─── 5. Financial Summary & Grand Total ──────────────────────────────────────

def test_financial_summary_and_grand_total_accuracy() -> None:
    """Subtotal, discounts, taxes, and grand total match exact stored values."""
    doc = _make_sample_metadata(
        subtotal=1250.00,
        discount=50.00,
        tax=115.00,
        total=1315.00,
    )
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    all_cells = [(cell.row, cell.column, cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]

    # Verify Grand Total cell exists with value 1315.00
    grand_total_matches = [val for _, col, val in all_cells if col == 5 and val == 1315.0]
    assert len(grand_total_matches) >= 1

    # Verify Subtotal
    subtotal_matches = [val for _, col, val in all_cells if col == 5 and val == 1250.0]
    assert len(subtotal_matches) >= 1


# ─── 6. Quality & Validation Information ─────────────────────────────────────

def test_quality_and_validation_signals_mapping() -> None:
    """Quality signals (confidence, arithmetic status, review flag) are displayed."""
    doc = _make_sample_metadata(
        confidence_level="HIGH",
        overall_confidence=0.98,
        total_matches=True,
    )
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    all_values = [str(cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]
    assert any("HIGH" in val for val in all_values)
    assert any("PASSED" in val or "VERIFIED" in val for val in all_values)


# ─── 7. Null & Missing Optional Fields Safety ─────────────────────────────────

def test_missing_optional_fields_safe_generation() -> None:
    """Minimal document with all optional fields missing generates cleanly without errors."""
    minimal_data = {
        "id": "11111111-1111-1111-1111-111111111111",
        "filename": "minimal_receipt.jpg",
        "created_at": None,
        "processed_at": None,
        "status": "completed",
        "extraction_result": {
            "vendor_company": None,
            "address": None,
            "date": None,
            "invoice_number": None,
            "subtotal": None,
            "tax": None,
            "total": 500.0,
            "line_items": [],
        },
        "quality_result": {},
    }

    excel_bytes = generate_document_excel_bytes(minimal_data)
    assert isinstance(excel_bytes, bytes)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active
    assert ws.cell(row=1, column=1).value == "STRUCTRA"

    all_values = [str(cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]
    assert any("No itemized line items extracted" in val for val in all_values)
    assert any(500.0 == cell.value for row in ws.iter_rows() for cell in row)


# ─── 8. Unicode & Special Characters Safety ──────────────────────────────────

def test_unicode_and_special_characters_support() -> None:
    """International characters, Hindi/Devanagari text, and special symbols work without crash."""
    unicode_doc = _make_sample_metadata(
        vendor="होटल ताज महल • Café Français & Sütçü Şakir",
        address="10, Kasturba Gandhi Marg, नई दिल्ली, 110001",
        line_items=[
            {"description": "मसाला चाय (Special Masala Tea)", "quantity": 3.0, "unit_price": 40.0, "line_total": 120.0},
            {"description": "Crème Brûlée à la vanille", "quantity": 1.0, "unit_price": 280.0, "line_total": 280.0},
        ],
        total=400.0,
    )

    excel_bytes = generate_document_excel_bytes(unicode_doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    all_values = [str(cell.value) for row in ws.iter_rows() for cell in row if cell.value is not None]
    assert any("होटल ताज महल" in val for val in all_values)
    assert any("मसाला चाय" in val for val in all_values)
    assert any("Crème Brûlée" in val for val in all_values)


# ─── 9. Decimal Precision Preservation ───────────────────────────────────────

def test_decimal_precision_is_preserved() -> None:
    """Non-trivial decimal fractions are preserved accurately."""
    doc = _make_sample_metadata(
        subtotal=199.99,
        discount=10.05,
        tax=34.14,
        total=224.08,
        line_items=[
            {"description": "Precision Item 1", "quantity": 1.5, "unit_price": 133.326, "line_total": 199.99},
        ],
    )
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    values = [cell.value for row in ws.iter_rows() for cell in row if isinstance(cell.value, (int, float))]
    assert 224.08 in values
    assert 199.99 in values
    assert 1.5 in values


# ─── 10. Filename Generator Tests ────────────────────────────────────────────

def test_export_filename_generation_and_sanitization() -> None:
    """Export filename uses STRUCTRA_EXPORT_<filename>.xlsx format and is sanitized."""
    # Standard original filenames
    data1 = ExportDocumentData(
        document_id="123",
        filename="receipt.jpg",
        vendor_name="D Mart",
        document_date="2026-07-29",
    )
    fn1 = generate_export_filename(data1)
    assert fn1 == "STRUCTRA_EXPORT_receipt.xlsx"
    assert not any(c in fn1 for c in '/\\:*?"<>|\x00')

    # Filename with spaces and extensions
    data2 = ExportDocumentData(
        document_id="123",
        filename="Dmart Receipt.jpeg",
        vendor_name="D Mart",
    )
    fn2 = generate_export_filename(data2)
    assert fn2 == "STRUCTRA_EXPORT_Dmart_Receipt.xlsx"

    # With illegal filesystem characters
    data3 = ExportDocumentData(
        document_id="123",
        filename="invoice/2026:08*final?.pdf",
    )
    fn3 = generate_export_filename(data3)
    assert not any(c in fn3 for c in '/\\:*?"<>|\x00')
    assert fn3.startswith("STRUCTRA_EXPORT_")
    assert fn3.endswith(".xlsx")

    # Missing filename fallback
    data4 = ExportDocumentData(
        document_id="123",
        filename="   ",
    )
    fn4 = generate_export_filename(data4)
    assert fn4 == "STRUCTRA_EXPORT_document.xlsx"


# ─── 11. Large Line Items List ───────────────────────────────────────────────

def test_large_line_items_list_handling() -> None:
    """Workbook handles 50+ line items with proper zebra striping and row indexing."""
    items = [
        {"description": f"Product Item #{i:02d}", "quantity": float(i), "unit_price": 10.0, "line_total": float(i * 10)}
        for i in range(1, 51)
    ]
    tot = sum(it["line_total"] for it in items)
    doc = _make_sample_metadata(line_items=items, total=tot, subtotal=tot)

    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    # Check 50 items rendered
    item_rows = [row for row in ws.iter_rows(values_only=True) if row[1] and str(row[1]).startswith("Product Item #")]
    assert len(item_rows) == 50
    assert item_rows[0][0] == 1
    assert item_rows[-1][0] == 50


# ─── 12. Visual Design & Print Setup Verification (Milestone 9.3) ────────────

def test_print_and_page_setup_configuration() -> None:
    """Print configuration is optimized for single-page width A4 portrait printing."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    assert ws.views.sheetView[0].showGridLines is True
    assert ws.page_setup.orientation == ws.ORIENTATION_PORTRAIT
    assert int(ws.page_setup.paperSize) == int(ws.PAPERSIZE_A4)
    assert ws.page_setup.fitToWidth == 1
    assert ws.page_setup.fitToHeight == 0


def test_table_header_and_total_row_styling() -> None:
    """Table headers and grand total rows have distinct styling, fills, and borders."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    # Check table header row fill and font color
    table_header_found = False
    for row in ws.iter_rows():
        if row[1].value == "Item Description":
            table_header_found = True
            assert any(c in str(row[1].font.color.rgb) for c in ["FFFFFF", "ffffff"])
            assert "0F172A" in str(row[1].fill.start_color.rgb).upper()
            break
    assert table_header_found

    # Check Grand Total row styling
    grand_total_found = False
    for row in ws.iter_rows():
        if row[0].value == "GRAND TOTAL:":
            grand_total_found = True
            assert "FFF7ED" in str(row[0].fill.start_color.rgb).upper()
            assert row[4].font.bold is True
            assert row[4].border.bottom.style == "double"
            break
    assert grand_total_found


def test_column_widths_configuration() -> None:
    """Column widths provide adequate breathing room and readability for descriptions."""
    doc = _make_sample_metadata()
    excel_bytes = generate_document_excel_bytes(doc)
    wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
    ws = wb.active

    assert ws.column_dimensions["A"].width >= 6
    assert ws.column_dimensions["B"].width >= 40  # Description column
    assert ws.column_dimensions["E"].width >= 20  # Financial values column

